
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPopupMenu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANDREA KAYLE
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        
        loginPage.setOpaque(false);
        loginPage.setContentAreaFilled(false);
        loginPage.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        createUser = new javax.swing.JTextField();
        registerAccount = new javax.swing.JButton();
        loginPage = new javax.swing.JButton();
        createPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        createEmail = new javax.swing.JTextField();
        selectAfl = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("LOG IN");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("REGISTER");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Full name");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Username");

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Email");

        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });

        registerAccount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerAccount.setText("NEXT");
        registerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAccountActionPerformed(evt);
            }
        });

        loginPage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginPage.setText("Already have an account? Click h̲e̲r̲e̲");
        loginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPageActionPerformed(evt);
            }
        });

        createPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPassActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Password");

        createEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmailActionPerformed(evt);
            }
        });

        selectAfl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        selectAfl.setText("SELECT AFFILIATION");
        selectAfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAflActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(fName, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(createUser, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(createPass, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(createEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(selectAfl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(registerAccount))
                    .addComponent(loginPage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addComponent(createEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(selectAfl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(registerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserActionPerformed

    private void registerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAccountActionPerformed

        String fullName = null, email = null, pass = null, userName = null, affiliate = null, query;
        String SUrl, SUser, SPass;
        
        SUrl = "jdbc:MySQL://localhost:3306/java_user_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement state = con.createStatement();
            
            if("".equals(fName.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Full name is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            else if("".equals(createEmail.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Email address is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            else if("".equals(createPass.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(createUser.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if("".equals(selectAfl.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Affiliation is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                fullName = fName.getText();
                email = createEmail.getText();
                pass = createPass.getText();
                userName = createUser.getText();
                affiliate = selectAfl.getText();
            }
            
            query = "INSERT INTO user(full_name, email, password, user_name,affiliation)" + 
                    "VALUES('"+fullName+"', '"+email+"', '"+pass+"','"+userName+"','"+affiliate+"')";
            
            state.execute(query);
            fName.setText("");
            createEmail.setText("");
            createPass.setText("");
            createUser.setText("");
            
            showMessageDialog(null, "Account has been created successfully!");
            
        }catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
        
    }//GEN-LAST:event_registerAccountActionPerformed

    private void loginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPageActionPerformed
        logIn login = new logIn();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_loginPageActionPerformed

    private void createPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPassActionPerformed

    private void createEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEmailActionPerformed

    private void selectAflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAflActionPerformed
 
        JPopupMenu popupMenu = new JPopupMenu(); 

        JMenuItem breeder = new JMenuItem("Breeder"); 
        JMenuItem shelter = new JMenuItem("Shelter"); 
        JMenuItem foster = new JMenuItem("Foster"); 
        
        breeder.addActionListener(new ActionListener() { 

            public void actionPerformed(ActionEvent e) { 

               selectAfl.setText("You're a Breeder");
            } 
        }); 

        shelter.addActionListener(new ActionListener() { 

            public void actionPerformed(ActionEvent e) { 

                selectAfl.setText("You're affliated with a Shelter");

            } 
        }); 
        foster.addActionListener(new ActionListener() { 

            public void actionPerformed(ActionEvent e) { 

                selectAfl.setText("You're a Foster");

            } 

        }); 

        popupMenu.add(breeder); 
        popupMenu.add(shelter); 
        popupMenu.add(foster); 

        selectAfl.addMouseListener(new MouseAdapter() { 

            public void mousePressed(MouseEvent e) { 

                showPopupMenu(e); 
            } 
            public void mouseReleased(MouseEvent e) { 

                showPopupMenu(e); 
            } 

            private void showPopupMenu(MouseEvent e) { 

                popupMenu.show(selectAfl, e.getX(), e.getY()); 
            } 
        }); 
        String affiliate = null, query; 
        String SUrl, SUser, SPass;
        
        SUrl = "jdbc:MySQL://localhost:3306/java_user_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement state = con.createStatement();
            
            
            if("".equals(selectAfl.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Affiliation is required", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                affiliate = selectAfl.getText();
            }
            
            query = "INSERT INTO user(affiliation)" + 
                    "VALUES('"+affiliate+"')";
            
            state.execute(query);
            
            showMessageDialog(null, "Account has been created successfully!");
            
        }catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
 
    }//GEN-LAST:event_selectAflActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField createEmail;
    private javax.swing.JPasswordField createPass;
    private javax.swing.JTextField createUser;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginPage;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerAccount;
    private javax.swing.JButton selectAfl;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
